base:
  appId: 123123123
  serverUrl: http://demo.dd.cn
  dingdingToken:

cmd:
  deploy:
    pre:
      host: 127.0.0.1
      user: root
      destDir: /home/dd/vv/dd/web
    test:
      host: 127.0.0.1
      user: root
      destDir: /home/dd/xx/dd/web
    dev:
      host: 127.0.0.1
      user: root
      destDir: /home/dd/scbbhool/22/web
